Website1/Models/Entities.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;

namespace Website1.Models
{
    public class Entities : DbContext
    {
        public Entities() : base("MyDB")
        {
        }
        public DbSet<admin> admins { get; set; }
        public DbSet<product> products { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Entity<admin>().ToTable("admins");
            modelBuilder.Entity<product>().ToTable("products");
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }

    }
}

Website1/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Website1.Models
{
    public class user
    {

    }
}

Website1/Models/admin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Website1.Models
{
    [Table("admins")]
    public class admin

    {
        [Key, Column(Order = 0)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Required]
        public String name { get; set; }

        [Key, Column(Order = 1)]
        [Required]
        public String email { get; set; }

        [Required]
        public String phone { get; set; }

        [Required]
        public String avatar { get; set; }

        [Required]
        public String password { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime created_at { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime updated_at { get; set; }

        [NotMapped]
        [Required]
        public string ConfirmPassword { get; set; }
    }
}

Website1/Models/product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Website1.Models
{
    public class product
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Required]
        public string pro_name { get; set; }

        [Required]
        public int pro_category_id { get; set; }

        [Required]
        public int pro_price { get; set; }

        [Required]
        public int pro_author_id { get; set; }

        [Required]
        public int discount { get; set; }

        [Required]
        public int final_price { get; set; }

        [Required]
        public int pro_quantity { get; set; }

        [Required]
        public String pro_description { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime created_at { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime updated_at { get; set; }

        [Required]
        public int size_S { get; set; }

        [Required]
        public int size_M { get; set; }

        [Required]
        public int size_L { get; set; }
    }
}

Website1/Areas/Admin/Controllers/AddAndEditAndRemoveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website1.Models;

namespace Website1.Areas.Admin.Controllers
{
    public class AddAndEditAndRemoveController : Controller
    {
        // GET: Admin/AddAndEditAndRemove
        private Entities db = new Entities();
        public ActionResult AddProduct()
        {
            if (Session["id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("LoginAdmin", "HomeAdmin");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProduct(product sp)
        {
            if (ModelState.IsValid)
            {
                var pro_name = sp.pro_name;
                var count = db.products.Where(s => s.pro_name.Contains(pro_name)).Count();
                if (count > 0)
                {
                    ViewBag.message = "San pham da ton tai, hay su dung Edit thay vì Add";
                    return View();
                }
                sp.pro_author_id = 1;
                sp.created_at = DateTime.Now;
                sp.updated_at = DateTime.Now;
                db.products.Add(sp);
                db.SaveChanges();
                return RedirectToAction("Index", "HomeAdmin");
            }
            ViewBag.message = "Them san pham that bai";
            return View();
        }
    }
}

Website1/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website1.Models;

namespace Website1.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: Admin/Home
        private Entities db = new Entities();
        public ActionResult Index()
        {
            if (Session["id"] != null)
            {
                var data = (from s in db.products select s).ToList();
                ViewBag.products = data;
                return View();
            }
            return RedirectToAction("LoginAdmin", "HomeAdmin");
        }
        public ActionResult LoginAdmin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginAdmin(String email, String password)
        {
            if (ModelState.IsValid)
            {
                var data = db.admins.Where(s => s.email.Equals(email) && s.password.Equals(password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["Name"] = data.FirstOrDefault().name;
                    Session["Email"] = data.FirstOrDefault().email;
                    Session["id"] = data.FirstOrDefault().id;
                    return RedirectToAction("Index", "HomeAdmin");
                }
                else
                {
                    ViewBag.error = "Login failed";
                }
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "HomeAdmin");
        }
    }
}

Website1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website1.Models;

namespace Website1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(String Email, String Password)
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(user user)
        {
            return View();
        }
        public ActionResult Products()
        {
            return View();
        }
    }
}

Website1/Areas/Admin/Views/AddAndEditAndRemove/AddProduct.cshtml
@model Website1.Models.product

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Add Product
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("AddProduct", "AddAndEditAndRemove", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label>pro_name</label>
                            @Html.TextBoxFor(m => m.pro_name, new { @class = "form-control", @placeholder = "pro_name" })
                        </div>
                        <div class="form-group">
                            <label>pro_category_id</label>
                            @Html.TextBoxFor(m => m.pro_category_id, new { @class = "form-control", @placeholder = "pro_category_id" })
                        </div>
                        <div class="form-group">
                            <label>pro_price</label>
                            @Html.TextBoxFor(m => m.pro_price, new { @class = "form-control", @placeholder = "pro_price" })
                        </div>
                        <div class="form-group">
                            <label>discount</label>
                            @Html.TextBoxFor(m => m.discount, new { @class = "form-control", @placeholder = "discount" })
                        </div>
                        <div class="form-group">
                            <label>final_price</label>
                            @Html.TextBoxFor(m => m.final_price, new { @class = "form-control", @placeholder = "final_price" })
                        </div>
                        <div class="form-group">
                            <label>pro_quantity</label>
                            @Html.TextBoxFor(m => m.pro_quantity, new { @class = "form-control", @placeholder = "pro_quantity" })
                        </div>
                        <div class="form-group">
                            <label>size_S</label>
                            @Html.TextBoxFor(m => m.size_S, new { @class = "form-control", @placeholder = "size_S" })
                        </div>
                        <div class="form-group">
                            <label>size_M</label>
                            @Html.TextBoxFor(m => m.size_M, new { @class = "form-control", @placeholder = "size_M" })
                        </div>
                        <div class="form-group">
                            <label>size_L</label>
                            @Html.TextBoxFor(m => m.size_L, new { @class = "form-control", @placeholder = "size.L" })
                        </div>
                        <div class="form-group">
                            <label>pro_description</label>
                            @Html.TextBoxFor(m => m.pro_description, new { @class = "form-control", @placeholder = "pro_description" })
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" value="Add Product" class="btn btn-success" />
                            @if (ViewBag.message != "")
                            {
                                <span class="badge badge-danger">@ViewBag.message</span>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Website1/Areas/Admin/Views/Home/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Website1/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Website1/Areas/Admin/Views/HomeAdmin/LoginAdmin.cshtml
@model Website1.Models.admin

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Login Admin
            </div>
            <div class="card-body">
                @using (Html.BeginForm("LoginAdmin", "HomeAdmin", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.email)
                        @Html.TextBoxFor(m => m.email, "", new { @class = "form-control", @placeholder = "Email" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.password)
                        @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Website1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/Shared/layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-2">
            <h1>Give Your Workout <br> A New Style!</h1>
            <p>Success isn't about greatness. It's about consistency. Consistent <br> hard work gains success. Greatness will come.</p>
            <a href="" class="btn">Explore Now &#8594;</a>
        </div>
        <div class="col-2">
            <img src="~/assets/images/image1.png">
        </div>
    </div>
</div>
<!-------- featured categories ---------->
<div class="categories">
    <div class="small-container">
        <div class="row">
            <div class="col-3"><img src="~/assets/images/category-1.jpg" alt=""></div>
            <div class="col-3"><img src="~/assets/images/category-2.jpg" alt=""></div>
            <div class="col-3"><img src="~/assets/images/category-3.jpg" alt=""></div>
        </div>
    </div>
</div>


<!-------- featured products ---------->
<div class="small-container">
    <h2 class="title">Featured Products</h2>
    <div class="row">
        <div class="col-4">
            <a href="product-details.html"><img src="~/assets/images/product-1.jpg" alt=""></a>
            <a href="product-details.html"><h4>Red Printed Tshirt</h4></a>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-2.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-3.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-4.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
    <h2 class="title">Latest Products</h2>
    <div class="row">
        <div class="col-4">
            <img src="~/assets/images/product-5.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-6.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-7.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-8.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <img src="~/assets/images/product-9.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-10.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-11.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-12.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
</div>

<!-------- offer ---------->
<div class="offer">
    <div class="small-container">
        <div class="row">
            <div class="col-2">
                <img src="~/assets/images/exclusive.png" class="offer-img">
            </div>
            <div class="col-2">
                <p>Exclusively Available on RedStore</p>
                <h1>Smart Band 4</h1>
                <small>The Mi Smart Band 4 features a 39.9% larger (than Mi Band 3) AMOLED color full-touch display with adjustable brightness, so everyting is clear as can be.</small>
                <a href="" class="btn">Buy Now &#8594;</a>
            </div>
        </div>
    </div>
</div>

<!-------- testimonial ---------->
<div class="testimonial">
    <div class="small-container">
        <div class="row">
            <div class="col-3">
                <i class="fa fa-quote-left"></i>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</p>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <img src="~/assets/images/user-1.png" alt="">
                <h3>Sean Parker</h3>
            </div>
            <div class="col-3">
                <i class="fa fa-quote-left"></i>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</p>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <img src="~/assets/images/user-2.png" alt="">
                <h3>Mike Smith</h3>
            </div>
            <div class="col-3">
                <i class="fa fa-quote-left"></i>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</p>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <img src="~/assets/images/user-3.png" alt="">
                <h3>Mabel Joe</h3>
            </div>
        </div>
    </div>
</div>

<!---------- brands ------------>
<div class="brands">
    <div class="row">
        <div class="col-5">
            <img src="~/assets/images/logo-godrej.png" alt="">
        </div>
        <div class="col-5">
            <img src="~/assets/images/logo-oppo.png" alt="">
        </div>
        <div class="col-5">
            <img src="~/assets/images/logo-coca-cola.png" alt="">
        </div>
        <div class="col-5">
            <img src="~/assets/images/logo-paypal.png" alt="">
        </div>
        <div class="col-5">
            <img src="~/assets/images/logo-philips.png" alt="">
        </div>
    </div>
</div>

Website1/Views/Home/Login.cshtml
@model Website1.Models.user

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/layout.cshtml";
}

Website1/Views/Home/Products.cshtml
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/layout.cshtml";
}

<div class="small-container">

    <div class="row row-2">
        <h2>All Products</h2>
        <select>
            <option>Default Sorting</option>
            <option>Sorted by price</option>
            <option>Sorted by popularity</option>
            <option>Sorted by rating</option>
            <option>Sorted by sale</option>
        </select>
    </div>

    <div class="row">
        <div class="col-4">
            <img src="~/assets/images/product-1.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-2.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-3.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-4.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <img src="~/assets/images/product-5.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-6.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-7.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-8.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <img src="~/assets/images/product-9.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-10.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-11.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
            <p>$50.00</p>
        </div>
        <div class="col-4">
            <img src="~/assets/images/product-12.jpg" alt="">
            <h4>Red Printed Tshirt</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>

    <div class="page-btn">
        <span>1</span>
        <span>2</span>
        <span>3</span>
        <span>4</span>
        <span>&#8594</span>
    </div>
</div>

Website1/Views/Home/Register.cshtml
@model Website1.Models.user

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/layout.cshtml";
}